-- Seed default showcase quotes if the table is empty.
-- Uses INSERT ... WHERE NOT EXISTS so it is safe to re-run (idempotent).

INSERT INTO "ShowcaseQuote" ("id", "author", "text", "source", "isDefault", "isEnabled", "sortOrder")
SELECT * FROM (VALUES
  ('quote-jobs-1',      'Steve Jobs',               'Design is not just what it looks like and feels like. Design is how it works.',                                                                                    'The New York Times, 2003',      true, true, 0),
  ('quote-jobs-2',      'Steve Jobs',               'The people who are crazy enough to think they can change the world are the ones who do.',                                                                          'Think Different campaign, 1997', true, true, 1),
  ('quote-jobs-3',      'Steve Jobs',               'Creativity is just connecting things.',                                                                                                                            'Wired, 1996',                   true, true, 2),
  ('quote-jobs-4',      'Steve Jobs',               'Stay hungry. Stay foolish.',                                                                                                                                       'Stanford commencement address, 2005', true, true, 3),
  ('quote-jobs-5',      'Steve Jobs',               'Simple can be harder than complex. You have to work hard to get your thinking clean to make it simple.',                                                           'BusinessWeek, 1998',            true, true, 4),
  ('quote-jobs-6',      'Steve Jobs',               'Innovation distinguishes between a leader and a follower.',                                                                                                        NULL,                            true, true, 5),
  ('quote-ive-1',       'Jony Ive',                 'We try to develop products that seem somehow inevitable.',                                                                                                         'Objectified documentary, 2009', true, true, 6),
  ('quote-ive-2',       'Jony Ive',                 'True simplicity is derived from so much more than just the absence of clutter and ornamentation.',                                                                 NULL,                            true, true, 7),
  ('quote-ive-3',       'Jony Ive',                 'The best ideas start as conversations.',                                                                                                                           NULL,                            true, true, 8),
  ('quote-rams-1',      'Dieter Rams',              'Good design is as little design as possible.',                                                                                                                     'Ten Principles for Good Design', true, true, 9),
  ('quote-rams-2',      'Dieter Rams',              'Good design is innovative.',                                                                                                                                       'Ten Principles for Good Design', true, true, 10),
  ('quote-rams-3',      'Dieter Rams',              'Good design makes a product useful.',                                                                                                                              'Ten Principles for Good Design', true, true, 11),
  ('quote-rams-4',      'Dieter Rams',              'Indifference towards people and the reality in which they live is actually the one and only cardinal sin in design.',                                              NULL,                            true, true, 12),
  ('quote-woz-1',       'Steve Wozniak',            'Never trust a computer you can''t throw out a window.',                                                                                                            'iWoz, 2006',                    true, true, 13),
  ('quote-woz-2',       'Steve Wozniak',            'My goal wasn''t to make a ton of money. It was to build good computers.',                                                                                          NULL,                            true, true, 14),
  ('quote-woz-3',       'Steve Wozniak',            'All the best things that I did at Apple came from not having money and not having done it before, ever.',                                                          NULL,                            true, true, 15),
  ('quote-kare-1',      'Susan Kare',               'Icons are the vocabulary of the visual language of the interface.',                                                                                                NULL,                            true, true, 16),
  ('quote-kare-2',      'Susan Kare',               'You want people to feel like they know how to use it just by looking at it.',                                                                                      NULL,                            true, true, 17),
  ('quote-raskin-1',    'Jef Raskin',               'An interface is humane if it is responsive to human needs and considerate of human frailty.',                                                                      'The Humane Interface, 2000',    true, true, 18),
  ('quote-raskin-2',    'Jef Raskin',               'The system should treat all user input as sacred.',                                                                                                                'The Humane Interface, 2000',    true, true, 19),
  ('quote-tog-1',       'Bruce Tognazzini',         'Consistency enables users to build accurate mental models of the way things work.',                                                                                 'AskTog',                        true, true, 20),
  ('quote-thinkdiff-1', 'Think Different campaign', 'Here''s to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes.',                                                      'Apple Inc., 1997',              true, true, 21)
) AS q(id, author, text, source, "isDefault", "isEnabled", "sortOrder")
WHERE NOT EXISTS (SELECT 1 FROM "ShowcaseQuote" LIMIT 1);
