/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c1c6d7',
        'error': '#ba1a1a',
        'surface': '#f9f9fe',
        'primary-container': '#0070eb',
        'surface-dim': '#d9dade',
        'outline': '#717786',
        'surface-bright': '#f9f9fe',
        'surface-variant': '#e2e2e7',
        'on-surface-variant': '#414755',
        'secondary': '#5d5e63',
        'surface-container-low': '#f3f3f8',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e2e2e7',
        'secondary-container': '#e0dfe4',
        'on-secondary-container': '#626267',
        'on-background': '#1a1c1f',
        'on-primary-container': '#fefcff',
        'on-surface': '#1a1c1f',
        'surface-container-high': '#e8e8ed',
        'surface-tint': '#005bc1',
        'surface-container': '#ededf2',
        'background': '#f9f9fe',
        'primary': '#0058bc',
        'tertiary': '#6f5d00',
        'tertiary-container': '#c5aa22',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#4b3f00',
        'tertiary-fixed': '#ffe261',
        'tertiary-fixed-dim': '#e2c53e',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
        'sans': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
